name: Build AvaloniaILSpy

on:
  push:
    branches: '**'
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Run the Cake script
      uses: cake-build/cake-action@v1
      with:
        script-path: build.cake
    - name: Zip Linux
      if: matrix.platform == 'ubuntu-latest'
      run: 7z a -tzip artifacts/ILSpy-linux-x64-Release.zip artifacts/linux-x64/*
    - name: Zip MacOS
      if: matrix.platform == 'macos-latest'
      run: 7z a -tzip artifacts/ILSpy-osx-x64-Release.zip artifacts/osx-x64/*
    - name: Zip Windows
      if: matrix.platform == 'windows-latest'
      run: 7z a -tzip artifacts\ILSpy-win-x64-Release.zip artifacts\win-x64\*      
    - name: Upload Linux artifacts
      if: matrix.platform == 'ubuntu-latest'
      uses: actions/upload-artifact@v2
      with:
        name: Linux x64 Release
        path: artifacts/ILSpy-linux-x64-Release.zip
        if-no-files-found: error
    - name: Upload Mac artifacts
      if: matrix.platform == 'macos-latest'
      uses: actions/upload-artifact@v2
      with:
        name: OSX x64 Release
        path: artifacts/ILSpy-osx-x64-Release.zip
        if-no-files-found: error
    - name: Upload Windows artifacts
      if: matrix.platform == 'windows-latest'
      uses: actions/upload-artifact@v2
      with:
        name: Windows x64 Release
        path: artifacts/ILSpy-win-x64-Release.zip
        if-no-files-found: error
